# This is the complete and corrected cloudbuild.yaml file

options:
  pool:
    name: "projects/geotech-cybersecurity/locations/me-central2/workerPools/sonarqube-worker-pool"
  logging: CLOUD_LOGGING_ONLY

steps:
  # This step runs the SonarQube scan.
  # It uses a shell entrypoint and the correct $$VAR syntax to escape secrets
  # for runtime expansion by the shell.
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'sh'
    secretEnv:
      - 'SONAR_HOST'
      - 'SONAR_TOKEN'
    args:
      - -c
      - |
        # Using $$VAR for secrets and ${_VAR} for substitutions
        sonar-scanner \
          -Dsonar.projectKey=pirate0x4d_vulnpy_e23b31f4-6b77-4104-bddb-15b03db2245b \
          -Dsonar.sources=. \
          -Dsonar.host.url=$$SONAR_HOST \
          -Dsonar.login=$$SONAR_TOKEN \
          -Dsonar.branch.name=${_BRANCH_NAME}

# This block tells Cloud Build to fetch the specified secrets from Secret Manager
# and make them available as environment variables to the build steps.
availableSecrets:
  secretManager:
    - versionName: projects/geotech-cybersecurity/secrets/SONAR_HOST_URL/versions/latest
      env: 'SONAR_HOST'
    - versionName: projects/geotech-cybersecurity/secrets/SONAR_LOGIN_TOKEN/versions/latest
      env: 'SONAR_TOKEN'

# This block defines user-defined variables.
# When used with a Cloud Build Trigger, _BRANCH_NAME will be automatically
# populated with the name of the branch that triggered the build.
substitutions:
  _BRANCH_NAME: 'master' # This is a default value if the build is run manually.
