# This is the complete cloudbuild.yaml file
# It increases the memory for the SonarScanner to prevent an OutOfMemoryError.

options:
  pool:
    name: "projects/geotech-cybersecurity/locations/me-central2/workerPools/sonarqube-worker-pool"
  logging: CLOUD_LOGGING_ONLY

# This is the service account the entire build will run as.
serviceAccount: 'projects/geotech-cybersecurity/serviceAccounts/sonar-build-runner@geotech-cybersecurity.iam.gserviceaccount.com'

steps:
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'sh'
    secretEnv:
      - 'SONAR_HOST'
      - 'SONAR_TOKEN'
    # Add environment variables to the build step
    env:
      # Increase the JVM heap size for the scanner. Default is often too low.
      - 'SONAR_SCANNER_OPTS=-Xmx2048m'
    args:
      - -c
      - |
        # This command runs the SonarScanner
        sonar-scanner \
          -Dsonar.projectKey=pirate0x4d_vulnpy_e23b31f4-6b77-4104-bddb-15b03db2245b \
          -Dsonar.sources=. \
          -Dsonar.host.url=$$SONAR_HOST \
          -Dsonar.login=$$SONAR_TOKEN \
          -Dsonar.branch.name=${_BRANCH_NAME} \
          -Dsonar.verbose=true

# This block tells Cloud Build to fetch the specified secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/geotech-cybersecurity/secrets/SONAR_HOST_URL/versions/latest
      env: 'SONAR_HOST'
    - versionName: projects/geotech-cybersecurity/secrets/SONAR_LOGIN_TOKEN/versions/latest
      env: 'SONAR_TOKEN'

# This block defines user-defined variables
substitutions:
  _BRANCH_NAME: 'master'
